-- Script de creación de base de datos y tablas para la API de AACH

CREATE DATABASE IF NOT EXISTS aach_db;

USE aach_db;

CREATE TABLE IF NOT EXISTS soap (
    NUM_POLIZA INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    PPU VARCHAR(10) NOT NULL,
    RIGE_DESDE DATETIME NOT NULL,
    RIGE_HASTA DATETIME NOT NULL,
    PRIMA INT NOT NULL
);