-- script de creacion bases de datos y tablas para la API del PRT

CREATE DATABASE IF NOT EXISTS prt_db;
USE prt_db;

-- Crear tabla REVISION_TECNICA (PRT)
CREATE TABLE REVISION_TECNICA (
    ID_REV_TECNICA INT AUTO_INCREMENT PRIMARY KEY,
    PPU VARCHAR(10),
    FECHA DATE,
    CODIGO_PLANTA VARCHAR(20),
    PLANTA VARCHAR(100),
    NOM_CERTIFICADO VARCHAR(100),
    FECHA_VENCIMIENTO DATE,
    ESTADO ENUM('aprobada', 'rechazada')
);

