-- Script para crear la base de datos y las tablas necesarias para la API de SRCEI

CREATE DATABASE IF NOT EXISTS srcei_db;

USE srcei_db;

CREATE TABLE IF NOT EXISTS PADRON (
    PPU VARCHAR(10) PRIMARY KEY,
    RUT VARCHAR(20),
    TIPO_VEHICULO VARCHAR(50),
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    ANIO INT,
    COLOR VARCHAR(30),
    CILINDRADA INT,
    NUM_MOTOR VARCHAR(50),
    NUM_CHASIS VARCHAR(50),
    FECHA_INSCRIPCION DATE
);

CREATE TABLE IF NOT EXISTS MULTAS_TRANSITO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PPU TEXT NOT NULL,
    ROL_CAUSA INT(11),
    JPL INT(11)
);
